const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const context=vm.createContext({URL,File,TextEncoder,AbortController,setTimeout,clearTimeout});
for(const file of ['core.js','download-attachments.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../../extension/src',file),'utf8'),context);
const A=context.SlackExporter;
const file={key:'file',name:'report',url:'https://team.slack.com/files/U1/F123/report.xlsx',downloadUrl:'https://files.slack.com/files-pri/T1-F123/download/report.xlsx'};
const snapshot={parents:[{files:[file],replies:[]}]};
(async()=>{
 let calls=0;
 context.fetch=async(url,options)=>{calls++;assert.equal(options.credentials,'include');assert.equal(options.redirect,'error');return new Response(new Uint8Array([80,75,3,4]),{headers:{'content-type':'application/octet-stream','content-length':'4'}});};
 const files=await A.downloadAttachments(snapshot);
 assert.equal(files[0].file.name,'report.xlsx');assert.equal(files[0].file.size,4);assert.equal(calls,1);
 await assert.rejects(()=>A.downloadAttachments({parents:[{files:[{...file,downloadUrl:'https://evil.test/file'}],replies:[]}]}),/supported download/);
 assert.equal(calls,1);
 context.fetch=async()=>new Response('<html>login</html>',{headers:{'content-type':'text/html'}});
 await assert.rejects(()=>A.downloadAttachments(snapshot),/web page instead/);
 const htmlSnapshot={parents:[{files:[{...file,downloadUrl:'https://files.slack.com/files-pri/T1-F123/download/report.html'}],replies:[]}]};
 await assert.rejects(()=>A.downloadAttachments(htmlSnapshot),/web page instead/);
 context.fetch=async()=>new Response('<html><h1>Report</h1></html>',{headers:{'content-type':'text/html','content-disposition':'attachment; filename="report.html"'}});
 const htmlFiles=await A.downloadAttachments(htmlSnapshot);
 assert.equal(htmlFiles[0].file.name,'report.html');
 assert.equal(await htmlFiles[0].file.text(),'<html><h1>Report</h1></html>');
 await assert.rejects(()=>A.downloadAttachments(snapshot),/web page instead/);
 context.fetch=async()=>new Response('truncated',{headers:{'content-length':'100'}});
 await assert.rejects(()=>A.downloadAttachments(snapshot),/truncated/);
 context.fetch=async()=>new Response('too large',{headers:{'content-length':String(A.LIMITS.maxMediaBytes+1)}});
 await assert.rejects(()=>A.downloadAttachments(snapshot),/size limit/);
 context.fetch=async()=>new Response('denied',{status:403});
 await assert.rejects(()=>A.downloadAttachments(snapshot),/HTTP 403/);
 console.log('PASS automatic attachments: authenticated download, file bytes, URL scope, login rejection, truncation, size and HTTP failures');
})().catch(e=>{console.error(e);process.exit(1);});
