const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1100,height:850}});
await page.route('https://app.slack.com/**',route=>route.fulfill({contentType:'text/html',body:`<html><body><div data-qa="channel_name">engineering</div><div class="p-message_pane"><div class="c-virtual_list__scroll_container" style="height:300px;overflow:auto"><div id="channel"></div></div></div><div id="side"></div></body></html>`}));await page.goto('https://app.slack.com/client/T123/C123');
await page.evaluate(()=>{const original=setTimeout;window.setTimeout=(fn,n)=>original(fn,Math.min(n,5));window.makeRow=(ts,text,replies=false)=>`<div data-item-key="${ts}" style="min-height:100px"><div class="c-message_kit__message"><span data-qa="message_sender_name">Byron</span><a data-ts="${ts}" href="https://a.slack.com/archives/C123/p${ts.replace('.','')}">12:00</a><div data-qa="message-text"><p>${text}</p><pre>const x = 1;</pre></div>${replies?'<button data-qa="reply_bar">2 replies</button>':''}</div></div>`;
 document.querySelector('#channel').innerHTML=makeRow('1780000000.000000','Older parent',true)+makeRow('1780000030.000000','Selected message')+makeRow('1780000050.000000','Outside range');
 document.querySelector('[data-qa="reply_bar"]').onclick=()=>{document.querySelector('#side').innerHTML='<div data-qa="thread_view"><button data-qa="close_thread">Close</button><div class="c-virtual_list__scroll_container" style="height:150px;overflow:auto">'+makeRow('1780000000.000000','Older parent')+makeRow('1780000031.000000','First reply')+makeRow('1780000032.000000','Second reply')+'</div></div>';document.querySelector('[data-qa="close_thread"]').onclick=()=>document.querySelector('#side').replaceChildren();};});
for(const f of ['core.js','adapter.js'])await page.addScriptTag({path:path.resolve(__dirname,'../../extension/src',f)});
const result=await page.evaluate(()=>SlackExporter.collect({range:{start:1780000030,end:1780000040,from:'test',to:'test',timezone:'UTC'},threads:true,olderThreads:true},{},()=>{}));
assert.equal(result.stopped,false);assert.equal(result.parents.length,2);assert.equal(result.parents[0].context,true);assert.equal(result.parents[0].replies.length,2);assert.equal(result.parents[0].threadWarning,undefined);assert.match(result.parents[1].text,/```/);assert.equal(result.parents[0].replies[0].text.includes('First reply'),true);console.log('PASS browser DOM capture, dates, older parent, thread opening, scrolling and ordering');
const cancelled=await page.evaluate(()=>SlackExporter.collect({range:{start:0,end:1900000000},threads:true,olderThreads:true},{cancelled:true},()=>{}));assert.equal(cancelled.stopped,true);assert.match(cancelled.warnings.join(),/Cancelled/);console.log('PASS browser cancellation preserves partial status');
// Simulate a virtualised list: its DOM contains only a moving window of rows.
await page.evaluate(()=>{const scroll=document.querySelector('.p-message_pane .c-virtual_list__scroll_container');document.querySelector('#side').replaceChildren();scroll.innerHTML='<div style="height:3000px;position:relative" id="virtual"></div>';const render=()=>{const first=Math.floor(scroll.scrollTop/100);document.querySelector('#virtual').innerHTML=Array.from({length:Math.min(5,30-first)},(_,i)=>'<div style="position:absolute;top:'+((first+i)*100)+'px;width:100%">'+makeRow(String(1780000100+first+i)+'.000000','Virtual '+(first+i))+'</div>').join('');};scroll.onscroll=render;scroll.scrollTop=0;render();});
const virtual=await page.evaluate(()=>SlackExporter.collect({range:{start:0,end:1900000000},threads:false,olderThreads:true},{},()=>{}));assert.equal(virtual.parents.length,30);assert.equal(virtual.stopped,false);console.log('PASS virtualised channel: all 30 messages recovered');
await page.close();await browser.close();})().catch(e=>{console.error(e);process.exit(1);});
