const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../extension');
const dom=new JSDOM(fs.readFileSync(path.join(root,'panel.html'),'utf8'),{url:'https://fixture.invalid/panel.html?tab=123',runScripts:'outside-only'});
const w=dom.window;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;
let collects=0,collectedOptions,finishBundle,finishDownloadRequest,downloadEvent,downloadFilename,downloadArgs,revoked=0,allowed=true;
const snap={title:'Original channel',exportedAt:'2026-09-07T12:00:00Z',range:{},url:'https://app.slack.com/client/T1/C1',parents:[],warnings:['fixture'],boundary:'test'};
w.chrome={permissions:{request:async()=>allowed},runtime:{id:'fixture',onMessage:{addListener(){}}},tabs:{sendMessage:async(_id,m)=>{if(m.type==='sce:collect'){collects++;collectedOptions=m.options;return {snapshot:snap};}return {ok:true};}},downloads:{onChanged:{addListener(fn){downloadEvent=fn;}},download:args=>{downloadArgs=args;downloadFilename=args.filename;return new Promise(resolve=>{finishDownloadRequest=resolve;});},search:async()=>[{state:'in_progress'}]}};
w.URL.createObjectURL=()=> 'blob:fixture';w.URL.revokeObjectURL=()=>{revoked++;};
w.eval(fs.readFileSync(path.join(root,'src/core.js'),'utf8'));
w.eval(fs.readFileSync(path.join(root,'src/download-attachments.js'),'utf8'));
w.SlackExporter.downloadAttachments=async()=>[];
w.SlackExporter.bundle=()=>new Promise(resolve=>{finishBundle=resolve;});
w.eval(fs.readFileSync(path.join(root,'panel.js'),'utf8'));
const $=id=>w.document.getElementById(id);
(async()=>{
 const tick=()=>new Promise(r=>setTimeout(r,0));
 $('media').checked=true;const saving=$('start').onclick();await tick();assert.equal(collects,1);
 assert.equal(collectedOptions.threads,true);assert.equal(collectedOptions.timestamps,true);assert.equal(collectedOptions.messageLinks,false);assert.equal(collectedOptions.olderThreads,true);
 assert.equal($('ack'),null);assert.equal($('save').hidden,true);assert.equal($('save').disabled,true);
 assert.equal($('start').disabled,true);assert.equal($('local'),null);
 for(const id of ['threads','timestamps','message-links','older','months'])assert.equal($(id),null);
 await $('start').onclick();assert.equal(collects,1);
 $('media').checked=false;await new Promise(r=>setTimeout(r,0));finishBundle(new w.Blob(['fixture']));await new Promise(r=>setTimeout(r,0));
 assert.equal(downloadFilename,'Original channel Channel - No messages.zip');
 assert.equal(downloadArgs.saveAs,false);assert.equal(downloadArgs.conflictAction,'uniquify');
 finishDownloadRequest(7);await saving;assert.equal($('start').disabled,true);
 downloadEvent({id:999,state:{current:'complete'}});assert.equal($('start').disabled,true);
 downloadEvent({id:7,state:{current:'interrupted'}});assert.equal($('start').disabled,false);assert.match($('status').textContent,/Interrupted/);assert.equal(revoked,1);
 assert.equal($('save').hidden,false);assert.equal($('save').textContent,'Retry download');
 const retry=$('save').onclick();await tick();finishBundle(new w.Blob(['fixture']));await tick();finishDownloadRequest(8);await retry;
 assert.doesNotMatch($('status').textContent,/Downloaded/);
 downloadEvent({id:8,filename:{current:'/Downloads/Original (1).zip'},state:{current:'complete'}});
 assert.equal($('status').textContent,'Downloaded: Original (1).zip');assert.equal($('save').hidden,true);
 $('from').value='2026-09-01';const next=$('start').onclick();await tick();assert.equal(collectedOptions.olderThreads,false);
 finishDownloadRequest(9);await next;downloadEvent({id:9,state:{current:'complete'}});
 assert.equal(downloadFilename,'Original channel.md');
 allowed=false;$('media').checked=true;await $('start').onclick();assert.equal(collects,2);assert.match($('status').textContent,/not granted/);assert.equal($('start').disabled,false);
 console.log('PASS panel: automatic download, pinned options, denied permissions, interruption/retry and browser-confirmed completion');
 dom.window.close();
})().catch(e=>{console.error(e);process.exit(1);});
